---

- name: set list
  set_fact:
    list: "{{ variables }}"
  tags: include

- name: include sub1
  include: sub1.yml
  with_items: "{{ list }}"
  loop_control:
    loop_var: var1
  when:
    - list is defined and list is iterable
    - condition
  tags: include

- name: include debug
  include: ../../debug/tasks/main.yml
  vars:
    var1: "{{ item }}"
  with_items: "{{ list }}"
  when:
    - list is defined and list is iterable
  tags: include
